# StopKorean Configuration file for version 1.00
# @author syamn <admin@sakura-server.net>
# Anti-Spamming Plugin!
# github: https://github.com/syamn/StopKorean

#==================#
#   Basic Config   #
#==================#
# Send warning messages when player speaking in Korean.
# Can use a colorcode(&0-&f) to warning message.
# default: false
WarnPlayer: false
WarnMessage: "&4[WARNING] Please use Japanese or English!"

# Kick player when speaking in Korean.
# default: true
KickPlayer: true
KickMessage: "Please use Japanese or English."

# NOTE: If both WarnPlayer and KickPlayer are true, KickPlayer setting will take precedence. So player kicked by server.
#       If both settings are false, nothing happens. And follow the CancelEvent setting.

# Logging violation Korean message to Console
# default: true
LogToConsole: true

# If it set to false, violation messages will be displayed to in-game chat, normally.
# default: true (Recommended)
CancelEvent: true

#=====================#
#   Herochat Config   #
#=====================#
# If you want to hook the Herochat, change this setting to true.
# If you changed this setting, need to server restart or use reload command.
# default: false
UseHerochat: false
# If UseHerochat set to true, specify the channels to censoring Korean.
# This channel settings can be reloaded when use "/stopkorean reload" command.
HerochatChannnels:
- Global
- Local
- World
