##  Plugin Information  ##
name: StopKorean
version: 1.0
main: syam.StopKorean.StopKorean
description: StopKorean for SakuraServer
website: http://sakura-server.net/
depend: [Herochat]
##  Original Author     ##
author: syam