##  Plugin Information  ##
name: StopKorean
version: 1.2
main: syam.StopKorean.StopKorean
description: StopKorean for SakuraServer
website: http://sakura-server.net/
depend: [Herochat]
##  Original Author     ##
author: syam
commands:
    stopkorean:
      usage: /honeychest - to see the help
      aliases: [sk]
      description: To see the Honeychest help.
permissions:
    stopkorean.reload:
        default: op
        description: Can reloading StopKorean configs.
    stopkorean.ignore:
        default: op
        description: Can speaking in Korean.