##  Plugin Information  ##
name: StopKorean
version: 2.0
main: syam.StopKorean.StopKorean
description: Stop Korean Spamming
website: http://sakura-server.net/
softdepend: [Herochat]
##  Original Author     ##
author: syam
commands:
    stopkorean:
      usage: /stopkorean - to see the help
      aliases: [sk]
      description: To see the StopKorean help.
permissions:
    stopkorean.reload:
        default: op
        description: Can reloading StopKorean configs.
    stopkorean.ignore:
        default: op
        description: Can speaking in Korean.